# ✅ Comando de compilación y carpeta de salida
[build]
  command = "npm run build"
  publish = "dist"

# ✅ Redirecciones: útil si usas rutas con JavaScript o SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# ✅ Opcional: Headers de seguridad (puedes quitarlos si no los necesitas)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'"

# ✅ Página de error personalizada
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404
